import { ArrowRight, ChevronRight, CircleAlert, CircleCheck, Clock3 } from "lucide-react";
import { useMemo, useState } from "react";
import { PageHeader } from "../../components/PageHeader";
import { PendingState } from "../../components/PendingState";
import { useQuery } from "@tanstack/react-query";

const measurements = ["Temperature", "Voltage", "Battery", "Pressure"];
const headers = ["Device", "Overall state", ...measurements, "Last processed"];

export function FleetPendingPage() {
  return <><PageHeader title="Fleet telemetry" detail="Live aggregate view · Awaiting first refresh" /><section className="status-strip" aria-label="Fleet status pending">{(["Critical", "Warning", "Stale", "Active"] as const).map((status) => <a className="status-metric" href="#fleet-table" key={status}><span>{status}</span><span className="skeleton-value" aria-hidden="true" /></a>)}</section><section className="panel fleet-panel"><div className="toolbar" aria-label="Fleet table controls"><label><span>Search fleet</span><input disabled placeholder="Device ID or name" type="search" /></label><label><span>State</span><select disabled defaultValue="all"><option value="all">All states</option></select></label><label><span>Measurement</span><select disabled defaultValue="all"><option value="all">All measurements</option></select></label><span className="toolbar__result">Awaiting fleet data</span></div><p className="sr-only" id="fleet-table-scroll-help">Scroll horizontally to review all fleet table columns.</p><div aria-describedby="fleet-table-scroll-help" aria-label="Fleet telemetry table" className="table-scroll" id="fleet-table" role="region" tabIndex={0}><table><caption className="sr-only">Fleet telemetry pending table</caption><thead><tr>{headers.map((header) => <th key={header} scope="col">{header}</th>)}</tr></thead><tbody>{Array.from({ length: 7 }, (_, index) => <tr key={index} aria-hidden="true">{headers.map((header) => <td key={header}><span className="skeleton-cell" /></td>)}</tr>)}</tbody></table></div><p className="panel-note">Fleet rows will appear when Redis live aggregates are connected.</p></section></>;
}

type FleetResponse = { mode: string; generated_at: string; summary: Record<string, number>; devices: Array<{ device_id: string; freshness: string; overall_status: string; last_processed_at: string; measurements: Array<{ measurement_type: string; latest_value: number }> }> };
const fetchFleet = async (): Promise<FleetResponse> => { const response = await fetch("/v1/live/fleet"); if (!response.ok) throw new Error("Live aggregates are unavailable"); return response.json(); };
export function FleetLivePage() { const query=useQuery({queryKey:["fleet-live"],queryFn:fetchFleet,refetchInterval:3000}); const [search,setSearch]=useState(""); const [filter,setFilter]=useState("all"); const [sort,setSort]=useState("device"); const data=query.data; const devices=useMemo(()=> (data?.devices??[]).filter(d=>(filter==="all"||d.freshness===filter||d.overall_status===filter)&&d.device_id.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==="device"?a.device_id.localeCompare(b.device_id):a.last_processed_at.localeCompare(b.last_processed_at)),[data,filter,search,sort]); if(!data&&query.isLoading)return <FleetPendingPage/>; if(!data)return <section className="recovery-state"><h1>Live data unavailable</h1><p>Redis live aggregates could not be loaded. No historical data was requested.</p></section>; const icon=(d:string)=>d==="critical"?<CircleAlert aria-hidden size={16}/>:d==="stale"?<Clock3 aria-hidden size={16}/>:<CircleCheck aria-hidden size={16}/>; return <><PageHeader title="Fleet telemetry" detail={`Live aggregate view · Updated ${new Date(data.generated_at).toLocaleTimeString()}`}/><section className="status-strip" aria-label="Fleet status">{["critical","warning","stale","active"].map(s=><button className="status-metric" onClick={()=>setFilter(s)} key={s}>{s}<strong>{data.summary[s]??0}</strong></button>)}</section>{query.isError&&<p className="panel-note">Degraded: showing last successful live snapshot.</p>}<section className="panel fleet-panel"><div className="toolbar"><label>Search fleet<input value={search} onChange={e=>setSearch(e.target.value)} type="search"/></label><label>State<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All states</option>{["critical","warning","stale","active"].map(s=><option key={s}>{s}</option>)}</select></label><button onClick={()=>{setSearch("");setFilter("all")}}>Clear filters</button><span className="toolbar__result">{devices.length} devices</span></div><div className="table-scroll" role="region" aria-label="Fleet telemetry table" tabIndex={0}><table><thead><tr>{headers.map(h=>{const active=(h==="Device"&&sort==="device")||(h==="Last processed"&&sort==="time");return <th key={h} scope="col" aria-sort={active?"ascending":"none"}><button onClick={()=>h==="Last processed"?setSort("time"):setSort("device")}>{h}</button></th>})}</tr></thead><tbody>{devices.length===0?<tr><td colSpan={7}>No devices match the current filters.</td></tr>:devices.map(d=><tr key={d.device_id}><td><a href={`/devices/${encodeURIComponent(d.device_id)}`}>{d.device_id}</a></td><td><span>{icon(d.overall_status)} {d.overall_status} · {d.freshness}</span></td>{measurements.map(m=>{const x=d.measurements.find(v=>v.measurement_type===m.toLowerCase());return <td className="numeric" key={m}>{x?x.latest_value:"—"}</td>})}<td className="numeric">{d.last_processed_at}</td></tr>)}</tbody></table></div></section></>; }

export function DevicePendingPage({ deviceID }: { deviceID: string }) {
  const breadcrumb = <><a href="/">Fleet</a><ChevronRight aria-hidden="true" size={16} /><span>{deviceID}</span></>;
  const action = <a className="button button--primary" href={`/devices/${encodeURIComponent(deviceID)}/history`}>View history <ArrowRight aria-hidden="true" size={16} /></a>;
  return <><PageHeader breadcrumb={breadcrumb} detail="Live aggregate view · Awaiting first device snapshot" title={deviceID} action={action} /><section className="fact-grid" aria-label="Device measurement facts pending">{measurements.map((measurement) => <PendingState key={measurement} label={`${measurement} pending`} rows={3} />)}</section><section className="chart-grid" aria-label="Device aggregate charts pending">{measurements.map((measurement) => <PendingState key={measurement} label={`${measurement} chart pending`} rows={5} />)}</section><p className="source-note">Data source: Redis live aggregate · Awaiting first device snapshot</p></>;
}
